// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[] args) {
        int n = Integer.parseInt(args[0]); 
        int below = 0;
        int over = 0;

        for (int i = 0; i < n; i++) {
            double r = Math.random();
            if (r < 0.5) below++;
            else over++;
        }
		double ratio = (double) over / below;

		System.out.println("> 0.5: " + (over)+" times");
		System.out.println("<= 0.5: " + (below)+" times");
		System.out.println( below ==0 || ratio==0 ? " " :"Ratio: " + ratio);
		
}
}